

#Produce CSV of Mean RR and Predicted Prob, by factors
```{r, echo=FALSE}
library(lme4)
library(aod)
library(Rcpp)
library(ggplot2)
library(plyr)
library(Rmisc)
library(scales)
library(Hmisc)
library(drc)
library(AICcmodavg)
library(multcomp)
library(nlme)
library(fields)
rm(list = ls())
Y <- (read.csv("/Users/devonrossman/Desktop/CSVforR/SoySdTrt/CSVFiles/CADnoCON.csv"))
Y3<-subset(Y, !(Y$Diff=="NA") & !(Y$sdtrt=="CON") 
           #& (Y$Year=="2015")
           )
Y3$stcost <- ifelse(Y3$sdtrt == "F", 4, ifelse((Y3$sdtrt =="F+I"), 10, 20))
Diff<-function(x){
  cry<-(Y3$stcost/(Y3$yield*x))
  diff<-(Y3$RR-cry)
  return(diff)
}
output<-as.data.frame(NULL)
for(i in c(6,10,14)){
DIFF<-Diff(i)
output_i<-cbind.data.frame(Y3, DIFF, i)
output<-rbind.data.frame(output,output_i)
}
output$soycost<-as.numeric(output$i)
output$Diff<-as.numeric(output$DIFF)
D<-output
D$N<-D$Diff
D$N <- ifelse(D$N < 0, 0, ifelse((D$N > 0), 1, 1))
D$var <- as.factor(D$var)
D$soycostsc<-scale(D$soycost)
D$Low5wksc<-scale(D$Low5wk)
D$Clay<-scale(D$Clay)
D$PD<-scale(D$PD)
D$West<-scale(D$West)
D$RF2wk<-scale(D$RF2wk)
mprob <- glmer(N ~ soycost + West + Low5wk + sdtrt + var + (1 | location) + (1 | Year) + (1 | rep/location), data=D, family=binomial)
summary (mprob)
BIC(mprob)

predictglm<-predictSE.merMod (mprob, D, se.fit = TRUE, type = "link", level=0, print.matrix = FALSE) 
Dglm <- cbind(D, predictglm)
Dglm <- within(Dglm, {
  PredictedProb <- plogis(fit)
  LL <- plogis(fit - (1.96 * se.fit))
  UL <- plogis(fit + (1.96 * se.fit))
  }
)
write.csv(Dglm, ("/Users/devonrossman/Desktop/CSVforR/SoySdTrt/CSVFiles/P/Prob.csv"))

Dglmprob <-( ddply(Dglm, c("sdtrt", "soycost", "location"), summarise,
                   RRmean=mean(RR),
               meanProb = mean(PredictedProb),
            Nmean=mean(N),
            ULmean=mean(LL),
              LLmean=mean(UL)))
write.csv(Dglmprob, ("/Users/devonrossman/Desktop/CSVforR/SoySdTrt/CSVFiles/P/GoodProbSummary.csv"))

```


Yield, By Year, Location, and Sdtrt
```{r, echo=FALSE}
library(ggplot2)
library(plyr)
library(Rmisc)
library(scales)
library(Hmisc)
library(multcomp)
library(nlme)
library(fields)
rm(list = ls())
Y <- (read.csv("/Users/devonrossman/Desktop/CSVforR/SoySdTrt/CSVFiles/CADJuly14.csv"))
Y3<-subset(Y, !(Y$Diff=="NA")
           )
Y3$stcost <- ifelse(Y3$sdtrt == "F", 4, ifelse((Y3$sdtrt =="F+I"), 10, 20))
Diff<-function(x){
  cry<-(Y3$stcost/(Y3$yield*x))
  diff<-(Y3$RR-cry)
  return(diff)
}
output<-as.data.frame(NULL)
for(i in c(6,10,14)){
DIFF<-Diff(i)
output_i<-cbind.data.frame(Y3, DIFF, i)
output<-rbind.data.frame(output,output_i)
}
output$soycost<-as.numeric(output$i)
output$Diff<-as.numeric(output$DIFF)
D<-output
D$N<-D$Diff

D1 <-( ddply(D, c("Year", "location", "sdtrt"), summarise,
            N=length(yieldMgha),
             meanyield=mean(yieldMgha),
            medianProb=median(yieldMgha),
            sdyield=sd(yieldMgha),
            seyield=(sdyield/sqrt(N))
                         ))
jpeg("Yield.jpeg", width = 8, height = 5, units = 'in', res = 300)
g<-ggplot(D1, aes(y=meanyield, x=sdtrt, fill=sdtrt))
g+
  geom_bar(stat= "identity")+ 
  theme_light()+
facet_grid(Year~location)+
  theme(text=element_text(color="black"), axis.text=element_text(size=8, angle=90, hjust=1),
    axis.title=element_text(size=10.5),
  strip.text=element_text(size=11, color="black"))+
  labs(x="Seed Treatment", y="Yield\nMg/kg", color="")
dev.off()
```


#Useful CorrPlots
```{r, echo=FALSE}
#install.packages("ggplot2")
library(ggplot2)
library(plyr)
library(Rmisc)
library(scales)
library(HSAUR)
library(Hmisc)
library(arm)
library(car)
library(corrplot)
library(graphics)
library(outliers)
library(ggpmisc)
#update.packages("corrplot")
#install.packages("outliers")
rm(list = ls())
Y <- (read.csv("/Users/devonrossman/Desktop/CSVforR/SoySdTrt/CSVFiles/LocationYearData.csv"))
Y3<-subset(Y, Y$Sdtrt=="Overall" 
           #& !(Y$pH=="5.9")
           )
Y5<-as.matrix(cbind(Y3$PRha, Y3$pH, Y3$CEC, Y3$SOM, Y3$Sand, Y3$Clay, Y3$W, Y3$Low5wk, Y3$RF2wk, Y3$PD))
colnames(Y5) <- c("Partial \nReturns", "pH", "CEC", "SOM", "Sand %", "Clay %", "West", "Low5wk", "RF2wk", "Planting \nDate")
corr2<-cor(Y5, use="pairwise.complete.obs")
Y6<-as.data.frame(Y5)
plot(Y6)
dev.off()
corrplot.mixed(corr2, lower="number", upper="shade" , tl.offset = 0, tl.pos="d", tl.cex=0.8)
corr1<-rcorr(Y5, type="pearson")
corr1

Y6<-as.data.frame(cbind(Y3$PRha, Y3$pH, Y3$CEC, Y3$SOM, Y3$Sand, Y3$Clay, Y3$Low5wk, Y3$RF2wk, Y3$PD))
Y6<-cbind(Y3$Location, Y6)
colnames(Y6) <- c("Site", "PartialReturns", "pH", "CEC", "SOM", "Sand",  "Clay", "Low5wk", "RF2wk", "PlantingDate")
Y6$Site<-as.factor(Y6$Site)

g<-ggplot(data=Y6, aes(x=PartialReturns, y=Clay))
gClay<-g+
  geom_point(
    aes(color=Site)
    )+theme(text=element_text(size=16))+
  geom_smooth(method = "lm", se=FALSE, color="black", formula = y ~ x, fullrange = TRUE) +
  stat_poly_eq(formula = y ~ x, 
               aes(label = paste(..eq.label.., ..adj.rr.label.., sep = "~~~")), 
               parse = TRUE)+
 stat_fit_glance(method = 'lm',
    method.args = list(formula = y ~ x),
    geom = 'text',
    aes(label = paste("P-value = ",    
    signif(..p.value.., digits = 4), sep = "")),
    label.x.npc = 'right', label.y.npc=0.35, size=3)

g<-ggplot(data=Y6, aes(x=PartialReturns, y=pH))
gpH<-g+
  geom_point(
    aes(color=Site)
    )+theme(text=element_text(size=16))+
  geom_smooth(method = "lm", se=FALSE, color="black", formula = y ~ x, fullrange = TRUE) +
  stat_poly_eq(formula = y ~ x, 
               aes(label = paste(..eq.label.., ..adj.rr.label.., sep = "~~~")), 
               parse = TRUE)+
 stat_fit_glance(method = 'lm',
    method.args = list(formula = y ~ x),
    geom = 'text',
    aes(label = paste("P-value = ",    
    signif(..p.value.., digits = 4), sep = "")),
    label.x.npc = 'right', label.y.npc=0.35, size=3)

g<-ggplot(data=Y6, aes(x=PartialReturns, y=SOM))
gSOM<-g+
  geom_point(
    aes(color=Site)
    )+ theme(text=element_text(size=16))+
  geom_smooth(method = "lm", se=FALSE, color="black", formula = y ~ x, fullrange = TRUE) +
  stat_poly_eq(formula = y ~ x, 
               aes(label = paste(..eq.label.., ..adj.rr.label.., sep = "~~~")), 
               parse = TRUE)+
 stat_fit_glance(method = 'lm',
    method.args = list(formula = y ~ x),
    geom = 'text',
    aes(label = paste("P-value = ",    
    signif(..p.value.., digits = 4), sep = "")),
    label.x.npc = 'right', label.y.npc=0.35, size=3)

multiplot(
gClay,
gpH,
gSOM,
cols=1)

chisq.out.test(Y6$PartialReturns, variance=var(Y6$PartialReturns), opposite=FALSE)

scatterplot(Y6$PartialReturns~Y6$Clay)
pairs(~Y6$PartialReturns + Y6$pH + Y6$SOM + Y6$Clay)
```


#Density Plot for SoySeedTrt
```{r, echo=FALSE}
library(ggplot2)
library(plyr)
rm(list = ls())
Y <- (read.csv("/Users/devonrossman/Desktop/CSVforR/SoySdTrt/CSVFiles/P/Prob.csv"))
y3<-subset(Y, (Y$soycost=="10"))
y4 <-( ddply(y3, c("location", "sdtrt"), summarise,
            meanProb=mean(PredictedProb),
            medianProb=median(PredictedProb)))
g<-ggplot(y3, aes(x=PredictedProb))
g+
  #geom_histogram(aes(y=..density..),bins=20)+
  theme_light()+
  theme(text=element_text(size=16))+
  geom_density(adjust=2)+
geom_vline(data=y4, aes(xintercept=meanProb, color="Mean"))+ 
  geom_vline(data=y4, aes(xintercept=medianProb, color="Median"))+
facet_grid(location~sdtrt)+
  theme(axis.text=element_text(size=10))+
  labs(x="Predicted Probability of Breaking Even", y="Predicted Outcomes", color="Averages")+
  scale_x_continuous(limits=c(0,1), breaks=c(0.1,0.2,0.3,0.4, 0.5, 0.6,0.7,0.8,0.9))

#700 Wide, 600 High for Image Export
```

Model Validation - Okay?
```{r, echo=FALSE}
library(pheatmap)
library(corrplot)
library(stats)
library(Hmisc)
rm(list=ls())
Y <- (read.csv("/Users/devonrossman/Desktop/CSVforR/SoySdTrt/CSVFiles/P/GoodProbSummary.csv"))
Y <- subset(Y, soycost=="10")
Y2<-as.matrix(cbind(Y$Nmean, Y$meanProb))
rownames(Y2)<-paste(Y$location, Y$sdtrt)
pheatmap(Y2, clustering_method="complete")

Y <- (read.csv("/Users/devonrossman/Desktop/CSVforR/SoySdTrt/CSVFiles/P/Prob.csv"))
Y <- subset(Y, soycost=="10")
Y2<-as.matrix(cbind(Y$N, Y$PredictedProb))
pheatmap(Y2, clustering_method="complete")
Y5<-as.matrix(cbind(Y$PredictedProb, Y$RR, Y$Diff, Y$PRha))
corr1<-rcorr(Y5, type="pearson")
corr1
```

#Field Isolate Chart
```{r, echo=FALSE}
library(ggplot2)
library(Rmisc)

Y <- (read.csv("/Users/devonrossman/Desktop/CSVforR/SoySdTrt/CSVFiles/FieldIsolates_July7.csv"))
YO<-subset(Y, !(Species=="") & (Pathogen=="O"))
YF<-subset(Y, !(Species=="") & (Pathogen=="F"))

YO <- within(YO, SpecGen <- factor(SpecGen,                    levels=names(sort(table(SpecGen),                                    decreasing=TRUE))))
YF <- within(YF, SpecGen <- factor(SpecGen,                    levels=names(sort(table(SpecGen),                                    decreasing=TRUE))))

    g1<-ggplot(YO, aes(x=SpecGen))+
geom_bar(data=YO, aes(fill=Location))+ 
theme_light()+
theme(axis.text=element_text(angle=90, hjust=1, vjust=0.5, size=12))+
labs(x="", y="Number of Isolates")+
ylim(0, 25)

     g2<-ggplot(YO, aes(x=SpecGen))+
geom_bar(data=YF, aes(x=SpecGen, fill=Location))+
theme_bw()+
theme(axis.text=element_text(angle=90, hjust=1, vjust=0.5, size=12))+
labs(x="", y="Number of Isolates")+ 
ylim(0, 50)

g1
g2
     
multiplot(g1, g2, cols=1)

```


#Greenhouse and Field Emergence/RDW Comparisons
```{r, echo=FALSE}
library(ggplot2)
library(lsmeans)
library(lme4)
library(Rmisc)
rm(list = ls())
#2015
Y <- (read.csv("/Users/devonrossman/Desktop/CSVforR/SoySdTrt/CSVFiles/CAD.csv"))
Y3<-subset(Y, !(Y$Diff8=="NA") #& !(Y$sdtrt=="CON") 
           & (Y$Year=="2015") 
           )
Y3$var<-as.factor(Y3$var)
lm1<-lmer(Scpubcont ~ sdtrt*var*YL + (1 | rep/YL), data=Y3)
lsm1<-lsmeans(lm1, pairwise~sdtrt:var | var)
a<-as.data.frame(summary(lsm1$lsmeans))
a12<-subset(a, !(a$var=="3") & !(a$var=="4"))

g<-ggplot(a12, aes(y=lsmean, x=var, color=sdtrt)
)+
  geom_point(position=position_dodge(width=0.21))+
   geom_errorbar(aes( ymin=a12$lsmean-1.96*a12$SE, ymax=a12$lsmean+1.96*a12$SE), width=0.2, position=position_dodge(width=0.21))+
  labs(y="Field Emergence \n Relative to NTC", x="Soybean Variety", color="Seed Treament")+
theme(axis.title=element_text(size=14), axis.text=element_text(size=12), legend.title=element_text(size=14), legend.text=element_text(size=12))
  
#GH
Y <- (read.csv("/Users/devonrossman/Desktop/CSVforR/GHData.csv"))
Y3<-subset(Y, !(Y$RDWcont=="NA") & !(Y$Var=="Sloan")
           #& (Y$PathTitle=="Control") 
           #& !(Y$sdtrt=="CON")
           )
Y3$Var<-as.factor(Y3$Var)
lm1<-lmer(Emergediffinsdtrt ~ sdtrt*Var + (1 | Rep/Exp), data=Y3)
lsm1<-lsmeans(lm1, pairwise~sdtrt | Var)
ab<-summary(lsm1)
ab<-as.data.frame(ab$lsmeans)
agh<-ab
gh<-ggplot(agh, aes(y=lsmean, x=Var, color=sdtrt)
)+ 
geom_point(position=position_dodge(width=0.21))+ 
geom_errorbar(aes(ymin=agh$lsmean-1.96*agh$SE, ymax=agh$lsmean+1.96*agh$SE), width=0.2, position=position_dodge(width=0.21))+
  labs(y="Greenhouse Emergence \n Relative to NTC", x="Soybean Variety", color="Seed Treament")+
theme(axis.title=element_text(size=14), axis.text=element_text(size=12), legend.title=element_text(size=14), legend.text=element_text(size=12))

#2015
Y <- (read.csv("/Users/devonrossman/Desktop/CSVforR/SoySdTrt/CSVFiles/CAD.csv"))
Y3<-subset(Y, !(Y$Diff8=="NA") #& !(Y$sdtrt=="CON") 
           & (Y$Year=="2015")
           )
Y3$var<-as.factor(Y3$var)
lm1<-lmer(RDWcont ~ sdtrt*var*YL + (1 | rep/YL), data=Y3)
lsm1<-lsmeans(lm1, pairwise~sdtrt:var | var)
a<-summary(lsm1$lsmeans)
a<-as.data.frame(a)
a13<-subset(a, !(a$var=="3") & !(a$var=="4"))

grdw<-ggplot(a13, aes(y=lsmean, x=var, color=sdtrt)
)+
  geom_point(position=position_dodge(width=0.21))+
   geom_errorbar(aes( ymin=a13$lsmean-1.96*a13$SE, ymax=a13$lsmean+1.96*a13$SE), width=0.2, position=position_dodge(width=0.21))+
  labs(y="Field Root Dry Weight \n Relative to NTC", x="Soybean Variety", color="Seed Treament")+
theme(axis.title=element_text(size=14), axis.text=element_text(size=12), legend.title=element_text(size=14), legend.text=element_text(size=12))

#GH 
Y <- (read.csv("/Users/devonrossman/Desktop/CSVforR/GHData.csv"))
Y3<-subset(Y, !(Y$RDWdiffinsdtrt=="NA") & !(Y$Var=="Sloan") 
           #& (Y$PathTitle=="Control")
           #& !(Y$sdtrt=="CON")
           )
Y3$Var<-as.factor(Y3$Var)
lm1<-lmer(RDWdiffinsdtrt ~ sdtrt*Var + (1 | Rep/Exp), data=Y3)
lsm1<-lsmeans(lm1, pairwise~sdtrt | Var)
a<-summary(lsm1)
a<-as.data.frame(a$lsmeans)
agh1<-a

ghrdw<-ggplot(agh1, aes(y=lsmean, x=Var, color=sdtrt)
)+ geom_point(position=position_dodge(width=0.21))+
geom_errorbar( aes(ymin=a$lsmean-1.96*a$SE, ymax=a$lsmean+1.96*a$SE, width=0.2), position=position_dodge(width=0.21))+
labs(y="Greenhouse Root Dry Weight \n Relative to NTC", x="Soybean Variety", color="Seed Treament")+
theme(axis.title=element_text(size=14), axis.text=element_text(size=12), legend.title=element_text(size=14), legend.text=element_text(size=12))

structure(ghrdw)
pq<-multiplot(g, grdw, gh, ghrdw, cols=2)

```
